service: diagnostic-tool

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs12.x
  stage: ${opt:stage, env:stage, "dev"}
  apiGateway:
    restApiId: !Ref PublicApiGateway
    restApiRootResourceId: !GetAtt PublicApiGateway.RootResourceId

custom:
  prune:
    automatic: true
    number: 5

functions:
  getHealthCheck:
    handler: src/handlers/getHealthCheck.handler
    events:
      - http:
          path: hc
          method: get
  slack-app:
    handler: src/handlers/slackApp.handler
    env:
      SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
      SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
      INCOMING_SNS_TOPIC_NAME: !GetAtt IncomingSlackMessageTopic.TopicName
    events:
      - http:
          path: slack/events
          method: get
      - http:
          path: slack/events
          method: post
  exampleHandleIncomingSlackMessage:
    handler: src/handlers/exampleHandleIncomingSlackMessage.handler
    events:
      - snsSqs:
          name: ExampleHandleIncomingSlackMessage # Required - choose a name prefix for the event queue
          topicArn: !Ref IncomingSlackMessageTopic # Required - SNS topic to subscribe to
  handleOutgoingSlackMessage:
    handler: src/handlers/handleOutgoingSlackMessage.handler
    events:
      - snsSqs:
          name: HandleOutgoingSlackMessage # Required - choose a name prefix for the event queue
          topicArn: !Ref OutgoingSlackMessageTopic # Required - SNS topic to subscribe to

resources:
  Resources:
    PublicApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: diagnostic-tool-publicApiGateway-${self:provider.stage}
        MinimumCompressionSize: 1024
        EndpointConfiguration:
          Types:
            - EDGE
    PublicApiGatewayDeployment:
      Type: AWS::ApiGateway::Deployment
      DependsOn:
        - ApiGatewayMethodHcGet
      Properties:
        RestApiId: !Ref PublicApiGateway
    IncomingSlackMessageTopic:
      Type: AWS::SNS::Topic
    OutgoingSlackMessageTopic:
      Type: AWS::SNS::Topic

  Outputs:
    PublicApiGateway:
      Description: The ID of the REST API.
      Value: !Ref PublicApiGateway
      Export:
        Name: PublicApiGateway-${self:provider.stage}
    PublicApiGatewayRootResource:
      Description: The ID of the root resource of the REST API.
      Value: !GetAtt PublicApiGateway.RootResourceId
      Export:
        Name: PublicApiGatewayRootResource-${self:provider.stage}

plugins:
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-offline
