service: diagnostic-tool

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs12.x
  stage: ${opt:stage, env:STAGE, dev}
  apiGateway:
    restApiId: !Ref PublicApiGateway
    restApiRootResourceId: !GetAtt PublicApiGateway.RootResourceId

custom:
  prune:
    automatic: true
    number: 5

functions:
  getHealthCheck:
    handler: src/handlers/getHealthCheck.handler
    events:
      - http:
          path: hc
          method: get

resources:
  Resources:
    PublicApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: diagnostic-tool-publicApiGateway-${self:provider.stage}
        MinimumCompressionSize: 1024
        EndpointConfiguration:
          Types:
            - EDGE
    PublicApiGatewayDeployment:
      Type: AWS::ApiGateway::Deployment
      DependsOn:
        - ApiGatewayMethodHcGet
      Properties:
        RestApiId: !Ref PublicApiGateway

  Outputs:
    PublicApiGateway:
      Description: The ID of the REST API.
      Value: !Ref PublicApiGateway
      Export:
        Name: PublicApiGateway
    PublicApiGatewayRootResource:
      Description: The ID of the root resource of the REST API.
      Value: !GetAtt PublicApiGateway.RootResourceId
      Export:
        Name: PublicApiGatewayRootResource

plugins:
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-prune-plugin
